### ISSUE TITLE
ability to have container dependencies

### ISSUE THREAD

**Issue by iangkent** [signalfuse/maestro-ng#119]
Currently maestro-ng supports service dependencies.

We would also like to have container dependencies within a service.

For example when we start an apache solr cluster we want the container acting as solr leader to start before other members/containers in the solr cluster.

**Comment by mpetazzoni** [comment]
I don't think I'll be implementing something like this. It would introduce a level of complexity that is useless in 99% of the cases. I would say you have two ways of solving your problem:

1. Either you make your Solr cluster be more intelligent about their leader election / connection to the leader (however that works), so that you don't need the leader to be up before the followers.
1. Or you make them two distinct logical services, one for the leader and one for the followers, which depends on the leader service.

In the latter case, you can heavily leverage Maestro's pre-processing of the YAML file via Jinja2 templating to remove most, if not all, of the YAML definition duplication between the two services.
